name: p3l_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^17.0.0
    
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  http: ^1.2.2

  shimmer: ^3.0.0

  intl: ^0.18.1
  awesome_dialog: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/white.png
      - assets/images/a.png

